### ISSUE TITLE
[beta to production issue] Pairing denied due to wrong email format

### ISSUE THREAD

**Issue by lhurt** [BjoernLange/openhab-miele-cloud-binding-beta#18]
Thank you for providing the binding. After the migration to 3.1.0 following [your guide here](https://github.com/BjoernLange/openhab-miele-cloud-binding-beta/releases/tag/v1.0.0-rc.1), repairing fails due to the error "Ihre Eingabe muss dem geforderten Format entsprechen".
It's the very same email address (miele@<mydomain>) that I already use for my Miele account and that I've successfully used before during the beta phase.

Can you please help me as I'm currently not able to use the binding.

**Comment by BjoernLange** [comment]
Hi @lhurt, I assume that you see this message in your browser when you try to re-authorize the account. This error means that your e-mail address isn't covered by the format validation which may be a problem with the format validation itself. Would you send me a PM containing the mail address please? You can also swap letters if you are concerned about privacy, but please do not replace special characters like `.`, `@`, etc. Then I can check what exactly the problem is and fix it.

For now, you can work around the problem by choosing a different e-mail address as identification for your account in the openHAB thing configuration and entering that one in the binding's UI when re-authorizing. You still need to use the "real" address when asked to log into the Miele Cloud Service.

This works because the e-mail address in openHAB is only used to identify the account thing locally. It is not checked against the Miele Cloud Service or verified in any other way so you can happily choose an e-mail address that doesn't match the one of your Miele Cloud Account (or even one that doesn't exist).

**Comment by lhurt** [comment]
@BjoernLange Thank you for the explanation. The affected email address is miele@hurt24.de. May be you can check what's going wrong. I suppose it's because of the miele part.

**Comment by lhurt** [comment]
@BjoernLange Any news on this? Seems like the numbers in the domain cause the issue.

**Comment by BjoernLange** [comment]
Hi @lhurt, sorry, I'm quite busy at the moment and did not have the time to tackle this, maybe I can fix it this weekend.

**Comment by Pusti47** [comment]
Hi! I have the same issue! But I use a - in my mail address (format like  nnnn@mmm-online.net). Clould you conider this please in your bug fix! Thx!

**Comment by lhurt** [comment]
@BjoernLange: BTW. The password restrictions on the main Miele site, where we have to have an account, are quite loose and insecure. The password has to be between 8-16 characters and two characters have to be numbers at least.

I will never understand why there's a length restriction and a character restriction as the passwords are saved as a salted hash where the length doesn't matter. The passwords are stored this way, aren't they?

Looks like a marketing restriction to me. Any chance you trigger an improvement on this issue?

**Comment by BjoernLange** [comment]
Please be aware that I'm not employed at Miele and thus have no knowledge of the internal workings of their cloud service @lhurt. However, I raised the issue in a discussion with them and they are going to investigate. That's all I can do in this regard and I cannot guarantee whether, how and when it will be changed.

**Comment by lhurt** [comment]
> Please be aware that I'm not employed at Miele and thus have no knowledge of the internal workings of their cloud service @lhurt. However, I raised the issue in a discussion with them and they are going to investigate. That's all I can do in this regard and I cannot guarantee whether, how and when it will be changed.

Thanks for the information. Please apologize for raising the issue. The way you are acting here is very professional and somehow it implied to me that you are an Miele employee. Nevertheless you were surprisingly agile which should have given already a hint that this is too fast for such a large company :-).

**Comment by BjoernLange** [comment]
> Thanks for the information. Please apologize for raising the issue. The way you are acting here is very professional and somehow it implied to me that you are an Miele employee. Nevertheless you were surprisingly agile which should have given already a hint that this is too fast for such a large company :-).

No problem! In fact I'm working for an IT consulting company and Miele tasked us with the development of this binding, so you weren't that far off :wink:

**Comment by BjoernLange** [comment]
@lhurt @Pusti47, I hoped that my PR would be merged a little faster this time but apparently that is not the case. Please try whether the bug is fixed for you in [this binding version](https://github.com/BjoernLange/openhab-miele-cloud-binding-beta/files/6824277/org.openhab.binding.mielecloud-3.2.0-SNAPSHOT.jar.zip) (you need to unzip it and copy the `.jar` file into your `addons` folder, I'm not sure whether you need to remove the existing binding first). I will release it as another beta version if it works for you.

**Comment by lhurt** [comment]
> @lhurt @Pusti47, I hoped that my PR would be merged a little faster this time but apparently that is not the case. Please try whether the bug is fixed for you in [this binding version](https://github.com/BjoernLange/openhab-miele-cloud-binding-beta/files/6824277/org.openhab.binding.mielecloud-3.2.0-SNAPSHOT.jar.zip) (you need to unzip it and copy the `.jar` file into your `addons` folder, I'm not sure whether you need to remove the existing binding first). I will release it as another beta version if it works for you.

@BjoernLange This snapshot is for 3.2-SNAPSHOP. Will it work with my 3.1 version?
Thanks

**Comment by BjoernLange** [comment]
Yes, @lhurt. My test installation is also running openHAB 3.1 and it works there.

**Comment by lhurt** [comment]
@BjoernLange Thanks a lot. It works now.
