### ISSUE TITLE
Bug report: Miele cloud startup error on OH 3.1.0 stable

### ISSUE THREAD

**Issue by ghost** [BjoernLange/openhab-miele-cloud-binding-beta#19]
# Miele cloud binding should just start

# binding start throws error:
2021-07-06 20:09:13.420 [ERROR] [Events.Framework                    ] - FrameworkEvent ERROR
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.mielecloud [29]
  Unresolved requirement: Import-Package: javax.measure; version="[1.0.0,2.0.0)"

# Environment

- Binding version: 
- openHAB version: 
- Running on: 
- Involved Miele devices: 

# Steps to Reproduce

1. 
2. 

# Possible Solution

# Additional information

**Comment by BjoernLange** [comment]
Hi @clh27! Thank you for your report. Unfortunately, that is too few information to pin down the issue. Which binding version are you using? A beta version or the stable one shipped with openHAB 3.1? Did you upgrade openHAB and run into this error now? If yes, what was the previous version and which binding version was used?

Just guessing what the problem could be: As this is the same error message encountered [here](https://community.openhab.org/t/miele-cloud-binding/93266/132), I assume you have been using openHAB 3.0 with `beta.5` and now upgraded to openHAB 3.1. If that is the case you need to upgrade to the stable version of the binding shipped with openHAB 3.1 because `beta.5` is not compatible with openHAB 3.1. Please make sure to remove the manually installed beta version. You will need to go through the [upgrade instructions for `rc.1`](https://github.com/BjoernLange/openhab-miele-cloud-binding-beta/releases/tag/v1.0.0-rc.1) if doing so. Please also be aware that there currently is a bug that prevents certain e-mail addresses from being used in the thing configuration, see [here](https://github.com/BjoernLange/openhab-miele-cloud-binding-beta/issues/18) for details.

**Comment by ghost** [comment]
thank you,
actually I was upgrading vom 3.1.0-M4 to 3.1.0 release.
After removal and purging of the release candidate binding and reinstalling it seems to work.

Thank you for the fast response, closing case
